### ISSUE TITLE
Certain posts only appear in play journal tab on internet archive and not on Archiverse

### ISSUE THREAD

**Issue by SNED72** [kyle1373/Archiverse#43]
I noticed while I was looking through a user's play journal on the internet archive, that there were posts that don't appear on the user's post list on Archiverse (or as a standalone post either). I do remember this being an issue on the previous site too, I always thought this was interesting, because I could find the posts on my personal archive downloaded from the IA as well so they definitely exist (ex: post AYMHAAADAAB2V0epeNNHNw is available on the Wayback Machine but throws an error saying "This post does not exist." on Archiverse). I am in no way very knowledgeable in coding and websites so I'm unsure if this is solvable but i figured I'd let you know! 

Also, love the site and thank you so much for reviving Archiverse!

**Comment by kyle1373** [comment]
Very interesting. I think this might be because the [database backup](https://archive.org/details/archiverse) which was based on the old and new site did not include your post for some reason. I've manually added your post to the database and is linked [here](https://archiverse.app/posts/AYMHAAADAAB2V0epeNNHNw). Let me know if anything is incorrect.

**Comment by SNED72** [comment]
Curious, I wonder how that happened! either way thank you for that! It looks good to me!
